# Generated by Django 3.2.9 on 2021-11-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_customer_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testApp.place')),
                ('serves_coffee', models.BooleanField(default=False)),
                ('serves_tuna', models.BooleanField(default=False)),
            ],
            bases=('testApp.place',),
        ),
    ]
