# Generated by Django 3.2.9 on 2021-11-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
